# Generated by Django 5.0.6 on 2024-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'user'), ('Admin', 'admin')], default='Pending', max_length=100),
            preserve_default=False,
        ),
    ]
