# Generated by Django 5.0.6 on 2024-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'user'), ('Admin', 'admin')], default='User', max_length=100),
        ),
    ]
